### ISSUE TITLE
[DSP] - Input audio distorts

### ISSUE THREAD

**Issue by NotActuallyErik** [Chowdhury-DSP/ChowMatrix#2]
**OS:** MacOS v10.15
**DAW:** FL-Studio 20.5.1 [Build 552]
**Sample-Rate:**  44.1khz

Audio sometimes distorts when played through nodes in ChowMatrix. Changing parameters inside the plugin does not resolve the issue. 

Enabling **Fixed Size Buffers** in FL-Studios plugin-wrapper fixes the issue, but this is obviously only possible in FL.

Fixed Size Buffers from the FL-Studio documentation: 

> **Use fixed size buffers** -This option can be useful in fixing rendering errors (glitching / timing issues) or crashes. FL Studio shares data with plugins using variable sized chunks of data (buffers). Some plugins require fixed sized buffers. While the VST specification allows hosts to use variable size buffers, some people don't care about specifications, so we provide this format since FL Studio uses variable sized buffers. If the additional options are both off (see below) the fixed buffer size option uses 2 ms. The disadvantage is that fixed size buffering can introduce an extra delay, depending on the audio buffer size selected in the Audio settings (F10). This delay is doubled for effects plugins. However, in some cases this setting may fix unwanted rendering delays and/or audio glitches caused by some plugins. 
>
>**Options:**
>These two options are only to be used if the default 2 ms 'Fixed sized buffers' does not work. In general, both these options >should be off.
>
>**Process maximum size buffers** - FL Studio block size is used as the fixed buffer size, the block size is the maximum >processing size, as determined by FL Studio itself. NOTE: The block size is typically a much bigger than the processing >buffer size, leading to even bigger latency.
>
>**Use maximum buffer size from host** - Same as the above but the plugin is also informed of the block size being used by >FL Studio. A few plugins can make use of this data to synchronize their processing.`

**Comment by jatinchowdhury18** [comment]
Hi Eric,

Thanks for reporting this. I've had this issue with another plugin of mine as well (see [here](https://github.com/jatinchowdhury18/AnalogTapeModel/issues/17#issuecomment-640199581)). It seems that FL Studio specifically uses some weird block sizes, that cause this issue (I haven't had this issue on any other DAW, for either plugin).

I'm not 100% sure what the cause of this issue is, but I have a theory: DAWs are supposed to report to the plugin the maximum length of the audio blocks passed in to the plugin. I use this value to allocate memory to store copies of that audio block wherever the plugin needs to (for example, see [here](https://github.com/Chowdhury-DSP/ChowMatrix/blob/9b8762b86e9a1bd8e82a35c0a28b02f6f882d365/src/ChowMatrix.cpp#L65) or [here](https://github.com/Chowdhury-DSP/ChowMatrix/blob/9b8762b86e9a1bd8e82a35c0a28b02f6f882d365/src/dsp/DelayNode.cpp#L111)). I'm guessing that FL Studio is passing in blocks of audio larger than the maximum reported block size, leading to a buffer over-read, which would cause the distortion you're noticing.

My proposed solution is to over-allocate my memory, to hopefully prevent these over-read's, but this is a weird thing to do because I don't know "how much" to over-allocate? I could over-allocate by 2x, but once FL Studio has broken the guarantee of the maximum allowed block size, it's really just a guessing game.

Anyway, I'll try a few experiments, and hopefully have some builds for you to try out in the next few days. In the meantime, enabling "Fixed size buffers" option should do the trick!

Thanks,
Jatin

**Comment by NotActuallyErik** [comment]
Honestly i know too little about how FL handles buffers to be of any help, but thank you for your answer - it's very interesting!

I'm by no means proficient with JUCE or even VST-dev in general, but if you have things you need to test and not enough time i'd happily help you out

**Comment by jatinchowdhury18** [comment]
Hi Erik,

I made some adjustments to how I'm handling the buffer sizes, and internal buffering in general. Would you mind giving them a test drive in FL: https://github.com/Chowdhury-DSP/ChowMatrix/tree/develop/bin

Side note: actually, I am using JUCE for this plugin, it just looks a little different from most JUCE-based projects, since I use the CMake build system (supported as of JUCE 6.0), along with a bunch of custom DSP and GUI code (most borrowed from other open-source projects).
