### ISSUE TITLE
[FEATURE] Linux VST support

### ISSUE THREAD

**Issue by Firedude1** [Chowdhury-DSP/ChowMatrix#47]
I would love to be able to use ChowMatrix on Linux with reaper (it dosen't support lv2 plugins). I have literally no experience with building VSTs and my _flawless_ plan of copy pasting the projucer builder from analogue tape model unsurprisingly did not work. Your help would be much appreciated!

Thanks!

**Comment by jatinchowdhury18** [comment]
Thanks for the question. Just to clarify, do you need the VST2 version, or does Reaper support VST3 plugin as well? VST3 should build "out of the box", but VST2 needs some extra steps since Steinberg doesn't allow the VST2 SDK to be distributed with the rest of the plugin code.

Also, I remember reading somewhere that Reaper might start supporting LV2 plugins soon...!

**Comment by Firedude1** [comment]
VST3 works great! Reaper LV2 is ever elusive ;)

**Comment by jatinchowdhury18** [comment]
Great! To use VST3 on Linux, here's what I do. First, build normally with CMake:
```
cmake -Bbuild
cmake --build build --config Release
```
Then copy the VST3 build to your VST3 path. For me this is
```
cp -R build/ChowMatrix_artefacts/VST3/ChowMatrix.vst3 ~/.vst3/
```
but it may be different depending on where your VST3 path is, and which CMake generator you're using.

Please let me know if you run into issues with this!

**Comment by Firedude1** [comment]
That works perfectly! I feel like a bit of an idiot right now. You might want to put the locations of the files in the Readme. Thanks for your help! The 5 minutes I spent playing with the plugin is the most fun I've had with a plugin in a while!

**Comment by Firedude1** [comment]
I proposed a commit with the changes I mentioned.

**Comment by jatinchowdhury18** [comment]
Awesome, thanks for the assist!
